{
	"version": 1647839835,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg.png",
		"images/ground.png",
		"images/player-sheet0.png",
		"images/groundon-sheet0.png",
		"images/groundon-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite3-sheet2.png",
		"images/skeleton.png",
		"images/start.png",
		"images/tree.png",
		"images/grass.png",
		"images/win.png",
		"images/enimy-sheet0.png",
		"images/tiledbackground.png",
		"images/coin-sheet0.png",
		"images/enemyfly-sheet0.png",
		"images/coinhud-sheet0.png",
		"images/bullet-sheet0.png",
		"images/endline-sheet0.png",
		"images/playbutton-sheet0.png",
		"images/playagainbutton-sheet0.png",
		"images/menubutton-sheet0.png",
		"media/jump.m4a",
		"media/jump.ogg",
		"media/nff-little-bonus.m4a",
		"media/nff-little-bonus.ogg",
		"media/swipe blade slash clang 03.m4a",
		"media/swipe blade slash clang 03.ogg",
		"media/melodyloops-the-first-light.m4a",
		"media/melodyloops-the-first-light.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}